name: Maven Tree Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Generate Maven Dependency Tree
        run: |
          find . -name "pom.xml" -execdir mvn dependency:tree -DoutputFile=maven_dep_tree.txt -Dmaven.test.skip=true \;
      - name: Upload Dependency Tree
        uses: actions/upload-artifact@v4
        with:
          name: maven-tree
          path: '**/maven_dep_tree.txt'

